resources:
- ../../base

patches:
- target:
    kind: Deployment
    name: nginx-app2
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 2
    - op: replace
      path: /spec/template/spec/containers/0/image
      value: docker.io/nginx:1.25
