apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: dv-vol1
  namespace: default
spec:
  source:
    blank: {}
  storage:
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 5Gi
    storageClassName: nfs-csi
---
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: dv-vol2
  namespace: default
spec:
  source:
    blank: {}
  storage:
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 5Gi
    storageClassName: nfs-csi
---
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: dv-vol3
  namespace: default
spec:
  source:
    blank: {}
  storage:
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 5Gi
    storageClassName: nfs-csi
