apiVersion: v1
kind: Pod
metadata:
  name: nfs-test-pod
  annotations:
    k8s.v1.cni.cncf.io/networks: default/secondary-net
spec:
  nodeName: worker-1
  containers:
    - name: test
      image: ubuntu:24.04
      command:
        - sleep
        - "3600"
      volumeMounts:
        - name: nfs-volume
          mountPath: /data

  volumes:
    - name: nfs-volume
      persistentVolumeClaim:
        claimName: nfs-test-pvc
